#!/bin/bash --login
#PBS -N EPPBE
#PBS -l select=12
#PBS -l walltime=03:00:00
#PBS -A pr1u1304

FOLDERS=(9 14 27)
NFOLDERS=${#FOLDERS[@]}
JOBS=/work/pr1u1304/pr1u1304/pr1uycu1/jobs/111
MPI=96

# Note: select = No. Nodes (24 CPUS per node) # Also from the architecture the sweet spots should be:
# 4 nodes (96 cores), which is one blade
# and multiples of four up to
# 64 nodes (1536 cores), which is one chassis.

# Hey lucy, if you need to c .. make sure you c - instead


# Make sure any symbolic links are resolved to absolute path
export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)

# Change to the directory that the job was submitted from.
cd $PBS_O_WORKDIR

# Set the number of threads to 1
# This prevents any system libraries from automatically 
# using threading.
export OMP_NUM_THREADS=1

# VASP makes big files
ulimit -s unlimited

for f in $FOLDERS
do
    zerof=$(printf "%03d" $f) 
    cd $JOBS/$zerof
    echo "Submitting job $JOBS/$zerof dotty...."    
    aprun -n $MPI /home/pr1u1304/pr1u1304/pr1uycu1/bin/vasp_std > vasp.out &
done

wait


